### PR TITLE
Document vital parts of the handshake

### PR DESCRIPTION
**Pull request by in1tiate**
why was this not documented before wtf

### CODE REVIEW

**Comment by cancer-name** [comment]
aoprotocol moment

**Review by oldmud0 — CHANGES_REQUESTED** [review]
It's already in the "Resource counts" section. This handshake section goes in the order that the conversation occurs in the desktop client. If you'd like you can add the `decryptor` message in the Obsolete > FantaCrypt section.

**Comment by in1tiate** [comment]
the vital part was always server `ID` without which the client will not complete the handshake

**Comment by oldmud0** [comment]
Don't know about serverside ID being required to finish the handshake, maybe I ignored it while I was writing ui-files and I based the docs off of what I had assumed was the bare minimum required.

**Pull request merged**
